# SPDX-License-Identifier: PolyForm-Noncommercial-1.0.0
function _schema_dictionary(schema_path::AbstractString)
    value = JSON3.read(read(schema_path, String))
    schema = _materialize_json(value)
    schema isa Dict{String,Any} ||
        throw(ServiceError("INVALID_REQUEST", "The protocol schema must be an object."))
    schema["schema"] == "aimora.service.protocol.v1" ||
        throw(ServiceError("INVALID_REQUEST", "The protocol schema identifier is unsupported."))
    return schema
end

function _cpp_string(value::AbstractString)
    return replace(String(value), "\\" => "\\\\", "\"" => "\\\"")
end

function _write_generated_header(io::IO, schema::Dict{String,Any}, schema_sha256::String)
    methods = schema["methods"]
    capabilities = sort!(unique(String[method["capability"] for method in methods]))
    error_codes = String.(schema["error_codes"])

    println(io, "// SPDX-License-Identifier: PolyForm-Noncommercial-1.0.0")
    println(io, "// Generated by AIMORAService/tools/generate_cpp_bindings.jl. Do not edit.")
    println(io, "#pragma once")
    println(io)
    println(io, "#include <QString>")
    println(io, "#include <QStringView>")
    println(io, "#include <array>")
    println(io, "#include <optional>")
    println(io, "#include <string_view>")
    println(io)
    println(io, "namespace aimora::studio::protocol::generated {")
    println(io)
    println(io, "inline constexpr std::string_view protocolVersion{")
    println(io, "    \"", _cpp_string(schema["protocol_version"]), "\"")
    println(io, "};")
    println(io, "inline constexpr std::string_view serviceVersion{")
    println(io, "    \"", _cpp_string(schema["service_version"]), "\"")
    println(io, "};")
    println(io, "inline constexpr std::string_view schemaSha256{")
    println(io, "    \"", schema_sha256, "\"")
    println(io, "};")
    println(io, "inline constexpr std::string_view frameMagic{")
    println(io, "    \"", _cpp_string(schema["frame"]["magic"]), "\"")
    println(io, "};")
    println(io, "inline constexpr int frameHeaderBytes = ", schema["frame"]["header_bytes"], ";")
    println(io, "inline constexpr unsigned char controlFrameKind = ", schema["frame"]["control_kind"], ";")
    println(io, "inline constexpr unsigned char binaryFrameKind = ", schema["frame"]["binary_kind"], ";")
    println(io)
    println(io, "enum class Method {")
    for method in methods
        println(io, "    ", method["cpp_name"], ",")
    end
    println(io, "};")
    println(io)
    println(io, "[[nodiscard]] QString methodName(Method method);")
    println(io, "[[nodiscard]] std::optional<Method> parseMethod(QStringView value);")
    println(io)
    println(io, "inline constexpr std::array<std::string_view, ", length(capabilities), "> capabilities{")
    for capability in capabilities
        println(io, "    \"", _cpp_string(capability), "\",")
    end
    println(io, "};")
    println(io)
    println(io, "inline constexpr std::array<std::string_view, ", length(error_codes), "> errorCodes{")
    for error_code in error_codes
        println(io, "    \"", _cpp_string(error_code), "\",")
    end
    println(io, "};")
    println(io)
    println(io, "} // namespace aimora::studio::protocol::generated")
end

function _write_generated_source(io::IO, schema::Dict{String,Any})
    methods = schema["methods"]
    println(io, "// SPDX-License-Identifier: PolyForm-Noncommercial-1.0.0")
    println(io, "// Generated by AIMORAService/tools/generate_cpp_bindings.jl. Do not edit.")
    println(io, "#include \"aimora/studio/protocol/generated/service_protocol.hpp\"")
    println(io)
    println(io, "namespace aimora::studio::protocol::generated {")
    println(io)
    println(io, "QString methodName(Method method) {")
    println(io, "    switch(method) {")
    for method in methods
        println(io, "    case Method::", method["cpp_name"], ":")
        println(io, "        return QStringLiteral(\"", _cpp_string(method["id"]), "\");")
    end
    println(io, "    }")
    println(io, "    return {};")
    println(io, "}")
    println(io)
    println(io, "std::optional<Method> parseMethod(QStringView value) {")
    for method in methods
        println(io, "    if(value == QStringView{u\"", _cpp_string(method["id"]), "\"}) {")
        println(io, "        return Method::", method["cpp_name"], ";")
        println(io, "    }")
    end
    println(io, "    return std::nullopt;")
    println(io, "}")
    println(io)
    println(io, "} // namespace aimora::studio::protocol::generated")
end

function generate_cpp_bindings(
    schema_path::AbstractString,
    header_path::AbstractString,
    source_path::AbstractString,
)
    schema = _schema_dictionary(schema_path)
    schema_sha256 = bytes2hex(SHA.sha256(read(schema_path)))
    mkpath(dirname(header_path))
    mkpath(dirname(source_path))
    open(header_path, "w") do io
        _write_generated_header(io, schema, schema_sha256)
    end
    open(source_path, "w") do io
        _write_generated_source(io, schema)
    end
    return schema_sha256
end
