name = "AIMORAProject"
uuid = "6e87310f-3ba6-4e69-9b4a-8a1fcbcc0c12"
version = "0.1.0"
authors = ["Ahmed Elkholy <ahmed_elkholy@f-eng.tanta.edu.eg>"]
license = "PolyForm-Noncommercial-1.0.0"

[compat]
julia = "1.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
