name = "AIMORAService"
uuid = "54bbdfc6-6134-4d5a-90dd-4d1a26642ec2"
version = "0.1.0"
authors = ["Ahmed Elkholy <ahmed_elkholy@f-eng.tanta.edu.eg>"]
license = "MIT"

[compat]
julia = "1.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
