name = "AIMORALayout"
uuid = "6f047e7d-bf2a-40ac-a20c-c55cfda68ba0"
license = "PolyForm-Noncommercial-1.0.0"
version = "0.1.0"
authors = ["Ahmed Elkholy <ahmed_elkholy@f-eng.tanta.edu.eg>"]

[deps]
AIMORAProject = "6e87310f-3ba6-4e69-9b4a-8a1fcbcc0c12"

[sources]
AIMORAProject = {path = "../AIMORAProject"}

[compat]
AIMORAProject = "1"
julia = "1.10"

[extras]
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Dates", "Test"]
