name = "AIMORALayout"
uuid = "6f047e7d-bf2a-40ac-a20c-c55cfda68ba0"
version = "0.1.0"
authors = ["Ahmed Elkholy <ahmed_elkholy@f-eng.tanta.edu.eg>"]
license = "PolyForm-Noncommercial-1.0.0"

[compat]
julia = "1.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
